POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "name": "Vaddisznó ragu erdei gombákkal, és bogyókkal",
  "type": "DISH",
  "description": "Frissen szedett erdei gombákkal, és vad gyükölcsökkel, bogyókkal párolt egytálétel",
  "preparationTime": [2,30],
  "cookingTime": [4,30]
}

###

GET http://localhost:8080/api/recipes
Accept: application/json

###

PUT http://localhost:8080/api/recipes/11
Content-Type: application/json

{
  "name": "Vaddisznó ragu erdei gombákkal, bogyókkal",
  "type": "DISH",
  "description": "Frissen szedett erdei gombákkal, vad gyükölcsökkel és bogyókkal párolt egytálétel",
  "preparationTime": [2,30],
  "cookingTime": [4,30]
}

###

DELETE http://localhost:8080/api/recipes/1
Accept: application/json

###

DELETE http://localhost:8080/api/recipes
Accept: application/json

###






POST http://localhost:8080/api/recipes/2/directions
Content-Type: application/json

{
  "directionText": "Elfőzzük a levet"
}

###

GET http://localhost:8080/api/recipes/2/directions
Accept: application/json

###


DELETE http://localhost:8080/api/recipes/2/directions
Accept: application/json

###


DELETE http://localhost:8080/api/recipes/directions
Accept: application/json

###

PUT http://localhost:8080/api/recipes/directions/7
Content-Type: application/json

{
  "direction": "Lassú tűzön, saját levében pároljuk, szükség esetén kevés vízzel pótoljuk az elfőtt levet"
}

###




GET http://localhost:8080/api/recipes/2/ingredients
Accept: application/json

###

POST http://localhost:8080/api/recipes/2/ingredients
Content-Type: application/json

{
  "name": "Vöröshagyma",
  "quantity": 1,
  "unit": "KG"
}

###

DELETE http://localhost:8080/api/recipes/ingredients
Accept: application/json

###

DELETE http://localhost:8080/api/recipes/1/ingredients
Accept: application/json

###

DELETE http://localhost:8080/api/recipes/ingredients/1
Accept: application/json

###

PUT http://localhost:8080/api/recipes/ingredients/1
Content-Type: application/json

{
  "direction": "Vöröshagyma",
  "quantity": 1500,
  "unit": "GRAM"
}

###




