POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "name": "Birkapörkölt karcagi módra",
  "type": "DISH",
  "description": "Egytálétel karcagi módra, koviubival",
  "preparationTime": [2,0],
  "cookingTime": [4,30]
}

###
